name: Generate Commit on Comment

on:
  issue_comment:
    types: [created]

jobs:
  generate-commit:
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/generate-commit')
    runs-on: ubuntu-latest

    steps:
      - name: Get branch name
        id: branch_name
        run: |
          branch_name=$(echo $GITHUB_REF | cut -d'/' -f 3)
          echo "::set-output name=branch_name::${branch_name}"
          echo $branch_name
      # jecho hello
      - name: Checkout
        uses: actions/checkout/@v3
        with:
          fetch-depth: 0

      - name: Git Identity
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
          current_branch=$(git rev-parse --abbrev-ref HEAD)
          git checkout -b main origin/main
          git checkout -b $current_branch
        env:
          GITHUB_TOKEN: ${{ github.token}}

      # - name: Setup Nodejs
      #   uses: actions/setup-node@v3
      #   with:
      #     cache: 'yarn'
      #     node-version: 16

      # - name: Install yarn
      #   run: npm install -g yarn@v1

      # - name: Install Dep
      #   run: |
      #     yarn install --frozen-lockfile
