# 为了试验，此处作为单独的 Workflow，在实际工作中可 Install -> Lint、Test -> Preview 串行检验
name: PULL REQUEST

# 执行 CI 的时机: 当 git push 到 feature-* 分支时
on:
  pull_request:
    branches: main

permissions:
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout/@v3
        with:
          fetch-depth: 0

      - name: Git Identity
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
          current_branch=$(git rev-parse --abbrev-ref HEAD)
          git checkout -b main origin/main
          git checkout $current_branch
        env:
          GITHUB_TOKEN: ${{ github.token}}

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: 16

      - name: Install yarn
        run: npm install -g yarn@v1

      - name: Install Dep
        run: |
          yarn install --frozen-lockfile

      - name: Update Pull Request
        run: |
          yarn changelog:ci
        env:
          GITHUB_TOKEN: ${{ github.token}}
          PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
